[package]
name = "SoundPalette"
version = "0.1.0"
edition = "2021"

[lib]
# cdylib is for use by browser JS as WebAssembly, rlib is for the Rust CLI app
crate-type = ["cdylib", "rlib"]
name = "libSoundPalette"

[[bin]]
name = "SoundPalette"
